//! # render_dot — 所有権グラフの Graphviz DOT 出力
//!
//! 解析層が組んだ Graph（Site/Var/Outside ノードと移譲エッジ）を
//! DOT 形式に落とす。`dot -Tsvg` で画像化できるほか、VSCode拡張の
//! グラフビューがこのDOT（またはGraphのJSON）を消費する想定。
//!
//! ノードIDは関数ごとに `f{n}_` を前置して衝突を避ける
//! （DOTのIDはファイル内グローバルなため）。

use crate::analysis::{GEdgeKind, GNodeKind, Report};
use std::fmt::Write;

pub fn render_dot(report: &Report) -> String {
    let mut d = String::new();
    let _ = writeln!(d, "// generated by cowl — 所有権グラフ");
    let _ = writeln!(d, "digraph cowl {{");
    let _ = writeln!(d, "  rankdir=LR; fontname=\"sans-serif\";");
    let _ = writeln!(d, "  node [fontname=\"sans-serif\", fontsize=11];");
    let _ = writeln!(d, "  edge [fontname=\"sans-serif\", fontsize=9];");

    for (fi, f) in report.functions.iter().enumerate() {
        // 関数ごとにクラスタ枠で囲み、視覚的な解析単位を明示する
        let _ = writeln!(d, "  subgraph cluster_{fi} {{");
        let _ = writeln!(d, "    label=\"{}\"; color=\"#d6d3d1\";", esc(&f.name));
        for nd in &f.graph.nodes {
            let (shape, fill) = match nd.kind {
                // Site=資源そのもの: 箱・teal / Var=名前: 楕円・白 / Outside: 灰
                GNodeKind::Site => ("box", "#ccfbf1"),
                GNodeKind::Var => ("ellipse", "#ffffff"),
                GNodeKind::Outside => ("doublecircle", "#f5f5f4"),
            };
            let _ = writeln!(
                d,
                "    f{fi}_{} [label=\"{}\", shape={shape}, style=filled, fillcolor=\"{fill}\"];",
                nd.id,
                esc(&nd.label)
            );
        }
        for e in &f.graph.edges {
            // エッジ種別ごとの見た目。Issue(二重free等)は coral 太線で強調
            let style = match e.kind {
                GEdgeKind::Bind => "color=\"#0d9488\"",
                GEdgeKind::Assign => "color=\"#6366f1\", style=dashed",
                GEdgeKind::Free => "color=\"#57534e\"",
                GEdgeKind::Escape => "color=\"#b45309\", style=dashed",
                GEdgeKind::Move => "color=\"#7c3aed\"",
                GEdgeKind::Issue => "color=\"#ef4444\", penwidth=2",
            };
            let _ = writeln!(
                d,
                "    f{fi}_{} -> f{fi}_{} [label=\"{}\", {style}];",
                e.from,
                e.to,
                esc(&e.label)
            );
        }
        let _ = writeln!(d, "  }}");
    }
    let _ = writeln!(d, "}}");
    d
}

fn esc(s: &str) -> String {
    s.replace('"', "\\\"")
}
